INSERT INTO tb_permissao(id, descricao) VALUES
(1, "ROLE_CADASTRAR_LANCAMENTO"),
(2, "ROLE_REMOVER_LANCAMENTO"),
(3, "ROLE_PESQUISAR_LANCAMENTO"),
(4, "ROLE_CADASTRAR_PESSOA"),
(5, "ROLE_REMOVER_PESSOA"),
(6, "ROLE_PESQUISAR_PESSOA"),
(7, "ROLE_CADASTRAR_CATEGORIA"),
(8, "ROLE_REMOVER_CATEGORIA"),
(9, "ROLE_PESQUISAR_CATEGORIA");